name: CI

on: [pull_request]

jobs:
  Build:
    name: Build on JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [1.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.0.7.7
      - name: Build project
        run: ./gradlew assemble
      - name: Run tests
        run: ./gradlew test
  Check:
    name: Check
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.0.7.7
      - name: Build project
        run: ./gradlew lint
      - name: Archive Lint report
        uses: actions/upload-artifact@v1
        with:
          name: Lint-report
          path: sample/build/reports/lint-results.html
  Espresso:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.0.7.7
      - name: Run instrumentation tests
        uses: hannesa2/action-android/emulator-run-cmd@0.0.7.7
        with:
          cmd: ./gradlew cAT
          api: 28
          tag: default
          abi: x86
      - name: Archive Espresso results
        uses: actions/upload-artifact@v1
        with:
          name: Espresso-report
          path: sample/build/reports/androidTests/connected
      - name: png-find
        run: find screenshots -name '*.png'
      - name: Archive screenshots
        uses: actions/upload-artifact@v1
        with:
          name: Screenshots-Moka
          path: screenshots/adb
