name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Build:
    name: Build on JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [ 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Build project
        run: ./gradlew assemble
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
        with:
          cmd: ./gradlew cAT
          api: 28
          tag: default
          abi: x86
          cmdOptions: -noaudio -no-boot-anim -no-window
      - name: Archive Espresso results
        uses: actions/upload-artifact@v2.3.0
        with:
          name: Espresso-report
          path: sample/build/reports/androidTests/connected
      - name: png-find
        run: find screenshots -name '*.png'
      - name: Archive screenshots
        uses: actions/upload-artifact@v2.3.0
        with:
          name: Screenshots-Moka
          path: screenshots/adb
  Check:
    name: Check
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - name: Build project
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v2.3.0
        with:
          name: Lint-report
          path: sample/build/reports/lint-results.html
