name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-13 ]
        api: [ 28 ]
        abi: [ x86_64 ]
        tag: [ 'default' ]
        include:
          #          - api: 31
          #            abi: x86_64
          #            tag: 'google_apis'
          - os: macOS-13
            api: 30
            abi: x86_64
            tag: 'google_apis'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.16.7
      - name: Build project
        run: ./gradlew assemble
      - name: Run instrumentation tests
        uses: hannesa2/action-android/emulator-run-cmd@0.1.16.7
        with:
          cmd: ./gradlew cAT --continue
          api: ${{ matrix.api }}
          tag: ${{ matrix.tag }}
          abi: ${{ matrix.abi }}
          cmdOptions: -noaudio -no-boot-anim -no-window
      - name: Archive Espresso results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Moka-Espresso-${{ matrix.api }}-${{ matrix.abi }}-report
          path: sample/build/reports/androidTests/connected
      - name: Archive screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Moka-Screenshots-${{ matrix.api }}-${{ matrix.abi }}-report
          path: |
            sample/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
            sample/build/outputs/androidTest-results/connected
  Check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-13 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/wrapper-validation-action@v3.3.2
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.16.7
      - name: Build project
        run: ./gradlew check
      - name: Archive Lint report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Lint-report
          path: sample/build/reports/lint-results*.html
