name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: kvm support
        run: |
          egrep -c '(vmx|svm)' /proc/cpuinfo
          id
          sudo adduser $USER kvm
          sudo chown -R $USER /dev/kvm
          id
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: hannesa2/action-android/install-sdk@0.1.16.7
      - run: sdkmanager platform-tools
      - run: ./gradlew nexusOneApi30DebugAndroidTest
      - name: Archive Espresso report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Moka-Espresso-report
          path: sample/build/reports/androidTests/connected
      - name: Archive Espresso results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Moka-Espresso-result
          path: sample/build/outputs/androidTest-results/managedDevice
      - name: Archive screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Moka-Screenshots
          path: |
            sample/build/outputs/connected_android_test_additional_output/debugAndroidTest/connected
            sample/build/outputs/androidTest-results/connected
  Check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/actions/wrapper-validation@v5
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.16.7
      - name: Build project
        run: ./gradlew check
      - name: Archive Lint report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Lint-report
          path: sample/build/reports/lint-results*.html
